game:
  genesis-enabled: false
  start-year: 1931
  player-nation-name: Deutschland
  turn-length: "6 month"
  current-date: "1.1.1931"
  gameEngineModel: "llmbg-tooluse-27b-v1.0-i1"

spring:
  application:
    name: TheParchmentThrone
  ai:
    openai:
      base-url: http://127.0.0.1:1235
      #      api-key: sk-12345 # Platzhalter-API-Schlüssel
      chat:
        options:
          #          model: llama-3-groq-8b-tool-use
          model: "llmbg-tooluse-27b-v1.0-i1"
    vectorstore:
      weaviate:
        host: localhost:9090
        scheme: http
