game:
  world-genesis:
    enabled: true
    start-year: 1931
    player-nation-name: Deutschland

spring:
  application:
    name: TheParchmentThrone
  ai:
    openai:
      base-url: http://127.0.0.1:1235
#      api-key: sk-12345 # Platzhalter-API-Schlüssel
      chat:
        options:
#          model: llama-3-groq-8b-tool-use
          model: llmbg-tooluse-27b-v1.0-i1
#    ollama:
##      base-url: http://127.0.0.1:1234
#      base-url: http://192.168.0.90:1234
#      chat:
#        model: llama-3.3-70b-instruct
#        options:
#          temperature: 0.7